# SPDX-FileCopyrightText: 2021-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-FileCopyrightText: 2021 Joas Schilling <coding@schilljs.com>
# SPDX-License-Identifier: GPL-3.0-or-later
# Configuration for probot-no-response - https://github.com/probot/no-response

# Number of days of inactivity before an Issue is closed for lack of response
daysUntilClose: 21
# Label requiring a response
responseRequiredLabel: "needs info"
# Comment to post when closing an Issue for lack of response. Set to `false` to disable
closeComment: >
  This issue has been automatically closed because there has been no response
  to our request for more information. With only the information that is
  currently in the issue, we don't have enough information to take action.
  Please reach out if you have or find the answers we need so that we can
  investigate further.
