# SPDX-FileCopyrightText: 2021-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-FileCopyrightText: 2022 Álvaro Brey <alvaro.brey@nextcloud.com>
# SPDX-FileCopyrightText: 2021 Joas Schilling <coding@schilljs.com>
# SPDX-License-Identifier: GPL-3.0-or-later
blank_issues_enabled: false
contact_links:
    -   name: Community Support and Help
        url: https://help.nextcloud.com/
        about: For questions and general help
